CREATE TABLE SubjectSchedFile (
    SSFEDPCODE VARCHAR(8) PRIMARY KEY,
    SSFSUBJCODE VARCHAR(15) NOT NULL,
    SSFSTARTTIME DATETIME NOT NULL,
    SSFENDTIME DATETIME NOT NULL,
    SSFDAYS VARCHAR(3) NOT NULL,
    SSFROOM VARCHAR(3) NOT NULL,
    SSFMAXSIZE INT NOT NULL,
    SSFCLASSSIZE INT NOT NULL,
    SSFSTATUS VARCHAR(3) NOT NULL, -- (Active, Inactive, Dissolved, Restricted, Closed)
    SSFXM VARCHAR(3) NOT NULL, -- (AM/PM)
    SSFSECTION VARCHAR(3) NOT NULL,
    SSFSCHOOLYEAR INT NOT NULL
);
