CREATE TABLE EnrollmentHeaderFile (
    ENRHFSTUDID BIGINT NOT NULL,
    ENRHFSTUDDATEENROLL DATETIME NOT NULL,
    ENRHFSTUDSCHLYR VARCHAR(15) NOT NULL,
    ENRHFSTUDENCODER VARCHAR(15) NOT NULL,
    ENRHFSTUDTOTALUNITS FLOAT NOT NULL,
    ENRHFSTUDSTATUS VARCHAR(2) NOT NULL CHECK (ENRHFSTUDSTATUS IN ('EN', 'UN')),
    PRIMARY KEY (ENRHFSTUDID)
);
