CREATE TABLE EnrollmentDetailFile (
    ENRDFSTUDID BIGINT NOT NULL,
    ENRDFSTUDSUBJCDE VARCHAR(15) NOT NULL,
    ENRDFSTUDEDPCODE VARCHAR(8) NOT NULL,
    ENRDFSTUDSTATUS VARCHAR(2) NOT NULL, -- (Withdrawn, Cancelled)
    PRIMARY KEY (ENRDFSTUDID, ENRDFSTUDEDPCODE)
);
