CREATE TABLE StudentGradeFile (
    SGFSTUDID BIGINT NOT NULL,
    SGFSTUDSUBJCODE VARCHAR(15) NOT NULL,
    SGFSTUDSUBJGRADE DOUBLE PRECISION NOT NULL,
    SGFSTUDEDPCODE VARCHAR(8) NOT NULL,
    SGFSTUDREMARKS VARCHAR(10),
    PRIMARY KEY (SGFSTUDID, SGFSTUDEDPCODE)
);
