CREATE TABLE StudentsRecord (
    STFSTUDID BIGINT DEFAULT (ABS(CHECKSUM(NEWID())) % (90000000) + (10000000)) PRIMARY KEY,
    STFSTUDLNAME VARCHAR(15) NOT NULL,
    STFSTUDFNAME VARCHAR(15) NOT NULL,
    STFSTUDMNAME VARCHAR(15),
    STFSTUDCOURSE VARCHAR(10) NOT NULL,
    STFSTUDYEAR INT NOT NULL,
    STFSTUDREMARKS VARCHAR(15) CHECK (STFSTUDREMARKS IN ('Shiftee', 'Transferee', 'New', 'Old', 'Cross-Enrollee', 'Returnee')),
    STFSTUDSTATUS VARCHAR(8) CHECK (STFSTUDSTATUS IN ('Active', 'Inactive')) NOT NULL DEFAULT 'Active'
);
