CREATE TABLE SubjectPreqFile (
    SUBJCODE VARCHAR(15) NOT NULL,
    SUBJPRECODE VARCHAR(15) NOT NULL,
    SUBJCATEGORY CHAR(2) NOT NULL CHECK (SUBJCATEGORY IN ('CR', 'PR')),
    PRIMARY KEY (SUBJCODE, SUBJPRECODE)
);
